### ISSUE TITLE
Gopher simple approach with probe selection using alignability maps

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#145]
See https://github.com/TheJacksonLaboratory/Gopher/issues/89
We should implement a simple approach that will choose the next best fragment if a fragment at the TSS does not satisfy the criteria of the user. Also implement a score that will give all TSS fragments 100% and will score other fragments according to their distance from the TSS. This will allow users of Gopher to manually check fragments that could not be made automatically.

**Comment by hansenp** [comment]
Another thing that would make the simple approach more interesting is the idea for probe selection in consideration of alignability and GC content described here: #113. This would have two further benefits:

1. It could also be used for the extended approach
2. It would streamline the overall workflow

Furthermore, this approach is more direct and precise as compared to just use the repeat content of the entire margin. Maybe many fragments could be _rescued_ in this way.

**Comment by hansenp** [comment]
I started to implement this feature. I created a class `AlignabiltyDownloader` and pushed to develop. I will now create a separate branch for further development.

**Comment by hansenp** [comment]
I managed to implement the download of the bigwig file which is a binary format. Furthermore, it is available only for mm9 and hg19.

The bigwig file has to be converted to bedgraph format before it can be processed. This usually requires a command line tool  `bedGraphToBigWig`. Maybe it is better to use a java library for this, e.g. https://github.com/lindenb/bigwig.

**Comment by hansenp** [comment]
I'm not sure about the best way to get the alignability information into Gopher. I see three options:

1. Convert the binary downloaded bigwig file (UCSC) into bed graph using `bigWigToBedGraph`. Then parse the bedgraph file. `bigWigToBedGraph` is a C++ program, which is part of a collection of small converter tools. But then Gopher would depend on this tool, and the users will have to download the executable file for their individual platform.

2. Implement or import code so that downloaded bigwig files (UCSC) become readable for Gopher. However, this seems to be a complex task. The source code of `bigWigToBedGraph` includes multiple header files, and the also the Java code (originally developed by the IGV team) looks complicated. I fear that this will be too much work. But maybe I'm wrong. @pnrobinson Could you please check and decide if this option is doable within reasonable time.

3. Make alignability maps in gzipped publically available. The difference in size is small:
```
120M Jun 12 08:28 wgEncodeCrgMapabilityAlign100mer.bedGraph.gz
 99M Jun 12 06:37 wgEncodeCrgMapabilityAlign100mer.bigWig
```
This would have the advantage that we could create additional alignability maps if required. Alignability maps from UCSC are available only for hg19 and mm9. @pnrobinson Is there a possibility to host such files at JAX?

@pnrobinson Do you have other ideas? What do you think? What is the best option?
