### ISSUE TITLE
Make Bait serializable

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#168]
or make these transient
```
 private List<Bait> baitListUpStreamMargin = null;
    private List<Bait> baitListDownStreamMargin = null;
```
otherwise we cannot serialize a model.

**Comment by hansenp** [comment]
In order to make Bait serializable I changed the class as follows:

`public class Bait implements Serializable {`

`static final long serialVersionUID = 1L;`

I can save the project before viewpoint creation. However, after viewpoint creation I get the following error message:

<img width="562" alt="screen shot 2018-07-10 at 3 19 20 am" src="https://user-images.githubusercontent.com/10495485/42495085-11931e8e-83f0-11e8-8bbc-a2b790046350.png">

**Comment by hansenp** [comment]
Has been solved in branch  `recordOriginalState`. I will close this issue.
