### ISSUE TITLE
“Cancle” button on the Example gene lists is not working

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#233]
Clicking the button does nothing and generates an exception.

![0](https://user-images.githubusercontent.com/5254933/43409920-84b2e698-9425-11e8-9dab-63b0ae5f63ff.png)

![image](https://user-images.githubusercontent.com/5254933/43409979-aee23d88-9425-11e8-9af6-63d4f3670686.png)

**Comment by pnrobinson** [comment]
I think you may not have the most up to date code, since I fixed this issue sometime on Sunday. I tried it a few times and it works. Please pull and try again, reopen this issue if needed.
I am not sure what you mean by hiding the buttons? 
Please close this issue if the cancel button now works. Please reopen a new issue about the layout/hiding the buttons!

**Comment by pnrobinson** [comment]
OK< now I understand -- I was checking another path through the GUI.
This could be fixed with
```
case CANCEL:
                    window.close();
                    break;
```
