### ISSUE TITLE
Scores always change to 100.0% with zoom

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#253]
Viewpoints below were generated with simple approach.

![score2](https://user-images.githubusercontent.com/5254933/43529700-26f17d02-95ac-11e8-8192-582e59416b3d.gif)

**Comment by pnrobinson** [comment]
Hmm....I can reproduce this bug.
The problem was here
```
  /**
     * Zoom in or out with the UCSC display.
     * @param factor If we zoom in, factor is {@link #ZOOMFACTOR}; if we zoom out, factor is 1/{@link #ZOOMFACTOR};
     */
    private void zoom(double factor) {
        logger.trace(String.format("Before zoom (factor %.2f) start=%d end =%d",factor,viewpoint.getStartPos(),viewpoint.getEndPos() ));
        this.viewpoint.zoom(factor);
        logger.trace(String.format("After zoom start=%d end =%d",viewpoint.getStartPos(),viewpoint.getEndPos() ));
        //updateScore();
        showColoredSegmentsInTable();
        showUcscView();
    }
```
in the ViewPointPresent class. I could fix this by commenting out the "updateScore".
However there is now a different bug. If you choose any digest, the score goes to 100 and if you then unchoose the other digest, the score does not return to the orginal level.

@hansenp  We should look at how the scores are getting calculated from ViewPointPresenter -- when we zoom, this changes the overall size of the display, and somehow this is affecting the score. I think there is a subtle bug. Maybe I can look at this on Friday, not sure, but if you can figure it out please try on Thursday

**Comment by hansenp** [comment]
The following lines are from the class `ViewPointPresenter`

![mage](https://user-images.githubusercontent.com/10495485/43576475-c39ff1f4-9649-11e8-9f36-c606068b8589.png)

@pnrobinson: But when/where is the state of the original viewpoint changed?

**Comment by hansenp** [comment]
I pushed a branch iss253 that contains the refresh function for viewpoint start and end position.

**Comment by pnrobinson** [comment]
``Now, the score changes, if I select an additional segment. But not if I deselect the the same segment.``
This is exactly the bug I am seeing here, not changed.

**Comment by pnrobinson** [comment]
#iss253 seems to have fixed the problem!
