### ISSUE TITLE
Manuscript-- consider how to revise this unclear passage

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#281]
of GOPHER, then GOPHER will select digest with at least 2 _ bmin valid probes.
If the two margins do not have equal numbers of probes, then the digest is referred
to as unbalanced. GOPHER prefers balanced to unbalanced digests because the
ends of targeted digests correspond to di_erent hybrid digests but to the same pair
of interacting digests. Therefore, all else equal, balanced digest may be associated
with more even enrichment. If it is preferable for the experimental goals to have
unbalanced digests rather than no digests at all for di_cult sequences, then the
unbalanced margins checkbox should be selected.

**Comment by hansenp** [comment]
@pnrobinson: How about this:

of GOPHER, then GOPHER will select digest with at least 2 _ bmin valid probes. If the two margins do not have equal numbers of probes, then the digest is referred to as unbalanced. Unbalanced digests correspond to different hybrid digests but to the same pair of interacting digests (Fig.2a). GOPHER prefers balanced to unbalanced digests because they may be associated with more even enrichment. However, if it is preferable for the experimental goals to have unbalanced digests rather than no digests at all for difficult sequences, then the user can allow for unbalanced margins or manually select individual digest after creation of viewpoints.

**Comment by pnrobinson** [comment]
revised this!
