### ISSUE TITLE
Gopher crash with mm10

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#302]
Even after updating the alignability map, GOPHER gets stuck after 14/22 mouse genes...

![gophercrash](https://user-images.githubusercontent.com/4943420/44870393-22781b00-ac5e-11e8-9b96-574d38520d46.png)

Gopher is frozen, and even clicking on Cancel does not stop the program.

**Comment by pnrobinson** [comment]
GOPHER also is crashing with hg19 (I also replaced the alignability map. 
I am seeing this
[ERROR] 08-30-2018 14:11:18 [ForkJoinPool.commonPool-worker-2] (ViewPoint.java:529) - SPEN At least one digest must contain 'genomicPos' (chr1:16169359-16175859)
![gophercrash2](https://user-images.githubusercontent.com/4943420/44870693-e1343b00-ac5e-11e8-834e-5ecaf3bdf2dd.png)

**Comment by hansenp** [comment]
I can reproduce the error with mm10. I also get a NullPointerException.

<img width="539" alt="screen shot 2018-08-31 at 1 07 00 am" src="https://user-images.githubusercontent.com/10495485/44893711-54b76600-acba-11e8-9b47-b4ff93aa24d7.png">

**Comment by hansenp** [comment]
I analyzed the case for a TSS of TPM3 at position 154,155,725. This TSS is located on a HindIII digest that has a length of about 11,000 bp and the distance to the start position of the adjacent digest in upstream direction is about 4900. The initial list of restriction fragments contains only digests within the range [4500;15000]. Therefore, the TSS-containing fragment is the first in the initial list. When GOPHER tries to add the adjacent fragment in upstream direction a `NullPointerException` is thrown.

<img width="715" alt="screen shot 2018-08-31 at 5 10 01 am" src="https://user-images.githubusercontent.com/10495485/44904576-a9b8a380-acdd-11e8-8f76-971640331445.png">

I can circumvent this exception by adding 500 bp in upstream direction to the range for initial restriction fragments (in class SegmentFactory.java).

<img width="553" alt="screen shot 2018-08-31 at 5 24 42 am" src="https://user-images.githubusercontent.com/10495485/44904813-39f6e880-acde-11e8-9b93-010aa88e9a92.png">

**Comment by hansenp** [comment]
I quick fix could be to increase the size of the range for the initial fragments. This could be done using fixed values or the estimated average size of all fragments. The solution with the estimated size has the advantage that it scales well with the chosen enzyme. However, the most failsafe solution would be to iteratively increase the size of the range as long as the TSS is on the first or last fragment of the list. In order to optimize the number of iterations, we could use the estimated average size as initial values. We need to make sure that this affects the simple approach only.

**Comment by hansenp** [comment]
I implemented the iterative solution with the estimated fragment size as initial values and applied GOPHER to the 32 human example genes. Already for this small number of genes there is (at least) one gene for which GOPHER needs to increase the initial size of the initial range for restriction fragments.

<img width="1088" alt="screen shot 2018-08-31 at 7 15 52 am" src="https://user-images.githubusercontent.com/10495485/44909715-674b9280-acee-11e8-86ba-1d160691df1f.png">

If I open the viewpoint tab for this gene, I can see that the TSS-containing and the adjacent fragment in downstream direction are very long.

<img width="1199" alt="screen shot 2018-08-31 at 7 25 48 am" src="https://user-images.githubusercontent.com/10495485/44909970-6bc47b00-acef-11e8-85b7-5443bda4d446.png">

**Comment by hansenp** [comment]
Another example is the gene NUB98:

<img width="1200" alt="screen shot 2018-08-31 at 7 31 42 am" src="https://user-images.githubusercontent.com/10495485/44910121-01600a80-acf0-11e8-872a-b5562bd45a18.png">

**Comment by hansenp** [comment]
I tested the new implementation on all protein coding genes. After 5319 viewpoints were successfully created GOPHER crashed with an IndexOutOfBounds exception. I guess this is due to a gene with a TSS near to the end but I was not yet able to find the gene for which the error occurred. I pushed the branch iss302 to the repository.

**Comment by hansenp** [comment]
GOPHER calculated viewpoints for all protein coding genes. If I sort the viewpoints by size I can see that the largest viewpoint is 20,000 bp.

![image](https://user-images.githubusercontent.com/10495485/45020633-ce8b7e80-b02f-11e8-9c32-7c8075b7acf4.png)

There is a threshold for the size of digests:

```
    /** Maximim allowable digest size for simple approach */
    private static final int SIMPLE_APPROACH_MAXSIZE=20_000;
```

@pnrobinson: What is the purpose of this threshold?

GOPHER is using lots of memory which might be due to the fact that the initial lists of digests are unnecessarily long (about 10 to 20). I will try to improve this. For the simple approach, the TSS-containing and the two adjacent digests are sufficient.

Furthermore, the size of the chromosome is determined two times using HTSJDK:

`int chromosomeLength = fastaReader.getSequence(this.getReferenceID()).length();`

This might be unnecessarily time consuming. I will also try to improve this.

Finally, the range for initial digests is still extended in both directions. In most of the iterations, it's enough to extend only in one direction. I will also try to improve this.

**Comment by pnrobinson** [comment]
I think we do not need SIMPLE_APPROACH_MAXSIZE anymore, this was part of some earlier approach that we do not need anymore.

**Comment by pnrobinson** [comment]
I revised the init() function in Viewpoint slightly.
Main chainges
1. The amount of extra sequence per iteration gets doubled each iteration
int increment = 1000; // before do..while
increment *= 2; // end of do..{}

2. I check whether the middle part of the loop changes anything because itherwise the position in GEOC at the end of the chromosome got into an infinite loop -- there was no cutting site downstream of genomicPos and so extending the downstream region did not help
```
 boolean changed=false;
(...)
  if(segmentFactory.getNumOfCutsUpstreamGenomicPos() < 2
                        && hasMoreSequenceUpstream() ) {
                    this.upstreamNucleotideLength = this.upstreamNucleotideLength + increment;
                    this.restrictionSegmentList.clear();
                    changed=true;
}
(same for other if-condition)
(...)
 while (changed && (segmentFactory.getNumOfCutsUpstreamGenomicPos() < 2 ||
                    segmentFactory.getNumOfCutsDownstreamGenomicPos() < 2) &&
                    !segmentFactory.maxDistUpOutOfChromosome() &&
                    !segmentFactory.maxDistDownOutOfChromosome());
```
3. This also means that we can get viewpoints with no central fragment -- therefore, I do not throw an exception if there is none 
```
 if (this.centerSegment==null) {
// log something and say so what
}
```
4. I also calculate the chromosome length once per chromosome and pass it as an argument to ViewPoint and Segment (I would hope that HTSJDK stores the value somewhere, but in the debugger it seemed to recalculate the value multiple times)

With these changes I ran All-Promoters for HindIII and every single gene got a Viewpoint, although many had a bad score. I am not sure if this is too good to be true. Also the smaller panels work with no errors @hansenp  please check!

**Comment by hansenp** [comment]
I tested with the gene GATA1 that has an unbalanced digests at the TSS (see Figure 3 in the manuscript). I did not allow for unbalanced margins. The list of viewpoints remains empty.

I thought we decided to show all viewpoints in the list, also those that could not be resolved. Bit this is not the case. Also for the summary statistics on the analysis tab the GATA1 gene is not taken into account.

<img width="747" alt="screen shot 2018-09-05 at 3 54 59 am" src="https://user-images.githubusercontent.com/10495485/45079069-861ba180-b0bf-11e8-9f3a-bb1cb2bde333.png">

I think this problem belongs to #322. I will reopen it.
