### ISSUE TITLE
resolving extended viewpoints

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#322]
In     ``public void generateViewpointExtendedApproach``

we have
```
boolean resolved=true;
(.... nothing to modify "resolved"
  setResolved(resolved);
```

Is this intentional, i.e., are extended viewpoints always resolvable? @hansenp

**Comment by hansenp** [comment]
No, I think originally we defined viewpoints at least one selected digest to resolved. Later on, we decided to show also unresolved viewpoints in the viewpoint table. Do we still need the resolved attribute for viewpoints?

**Comment by pnrobinson** [comment]
I do not think we need a separate variable for resolved -- if we want to know if a viewpoint is resolved, we can just count the active segments.

**Comment by pnrobinson** [comment]
I have removed the "resolved" and made a few slight adjustments. getResolved was only used in the Design class (and a few test classes) and so I replaced it with hasValidProbe().

**Comment by hansenp** [comment]
We should rename the function `hasValidProbe()` to `hasValidDigest()`, otherwise it might be confusing at a later time.

**Comment by hansenp** [comment]
I reopen this issue because I believe there is no consistent definition of resolved viewpoints for the simple and extended approaches.

For the extended approach we formerly decided that a viewpoint is resolved if it has at least one selected digest. For the simple approach we formerly decided that a viewpoint is resolved if the digest at the TSS is selected.

In the end, we decided to abolish resolved and unresolved viewpoints and to show all viewpoints in the list on the analysis tab. However, if I test for `GATA1` which has no balanced digest at the TSS with `Allow unbalanced?` set to `false`, the list remains empty. Furthermore, `GATA1` is not taken into account for the summary statistics.

<img width="747" alt="screen shot 2018-09-05 at 3 54 59 am" src="https://user-images.githubusercontent.com/10495485/45080189-54f0a080-b0c2-11e8-906c-862711f0fc01.png">

**Comment by hansenp** [comment]
I renamed the function `hasValidProbe` to `hasValidDigest`. Then I changed the following code in class ViewPoints:

```
            if (vp.hasValidDigest()) {
                viewpointlist.add(vp);
                logger.trace(String.format("Adding viewpoint %s to list (size: %d)", vp.getTargetName(), viewpointlist.size()));
            } else {
                logger.trace(String.format("Skipping viewpoint %s (size: %d) because it was not resolved", vp.getTargetName(), viewpointlist.size()));
            }
```

to

```
            if (1==1) {
                viewpointlist.add(vp);
                logger.trace(String.format("Adding viewpoint %s to list (size: %d)", vp.getTargetName(), viewpointlist.size()));
            } else {
                logger.trace(String.format("Skipping viewpoint %s (size: %d) because it was not resolved", vp.getTargetName(), viewpointlist.size()));
            }
```

Then I tested again for GATA1. Now it is shown in the list and also taken into account for the summary statistics.

<img width="1199" alt="screen shot 2018-09-05 at 4 31 52 am" src="https://user-images.githubusercontent.com/10495485/45081194-a8fc8480-b0c4-11e8-9077-e57946a38137.png">

**Comment by hansenp** [comment]
Next, I tested GATA1 with the extended approach, upstream size = 5000 and downstream size = 1500 and `Allow unbalanced?` set to false. For these settings I get an error message:

```
[ERROR] 09-05-2018 04:49:10 [Thread-10] (ViewPoint.java:498) - center segment NUll for GATA1
	maxSizeUp=5000, maxSizeDown=1500 size of restrictionFragmentList =2
[ERROR] 09-05-2018 04:49:10 [Thread-10] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for GATA1
```
This is strange because this worked for previous versions of GOPHER (see Figure 6b).

**Comment by hansenp** [comment]
The viewpoint for GATA1 is shown in the list and taken into account for summary statistics.

<img width="1186" alt="screen shot 2018-09-05 at 4 58 34 am" src="https://user-images.githubusercontent.com/10495485/45082899-6177f780-b0c8-11e8-93f0-65cab85b6cfa.png">
 
If I open the viewpoint tab, I can see that there are only two digests that are not selected. If I select these digests, I can see that they have a strange location.

<img width="1197" alt="screen shot 2018-09-05 at 5 01 32 am" src="https://user-images.githubusercontent.com/10495485/45083062-cc293300-b0c8-11e8-8f00-411b1510131b.png">

**Comment by hansenp** [comment]
Next, I tested 1000 randomly selected gene symbols with the simple approach and DpnII. Viewpoints without selected digests are taken into account for the summary statistics and are shown in the list.

<img width="1189" alt="screen shot 2018-09-05 at 6 14 57 am" src="https://user-images.githubusercontent.com/10495485/45087278-4fe81d00-b0d3-11e8-9e7f-eef33244f8a1.png">

If I do the same for the extended approach with default upstream and downstream sizes, I get lots of error messages:

```
[ERROR] 09-05-2018 06:24:16 [Thread-6] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for PMS2P7
[ERROR] 09-05-2018 06:24:32 [Thread-6] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for FOXD4L5
[ERROR] 09-05-2018 06:24:32 [Thread-6] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for ANKRD20A4-ANKRD20A20P
[ERROR] 09-05-2018 06:24:33 [ForkJoinPool.commonPool-worker-0] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for BMS1P14
[ERROR] 09-05-2018 06:24:33 [ForkJoinPool.commonPool-worker-0] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for LOC102724580
[ERROR] 09-05-2018 06:24:41 [Thread-6] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for GAGE6
[ERROR] 09-05-2018 06:24:41 [Thread-6] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for GAGE6
[ERROR] 09-05-2018 06:24:42 [Thread-6] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for GAGE2D
[ERROR] 09-05-2018 06:24:42 [Thread-6] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for GAGE2D
[ERROR] 09-05-2018 06:24:43 [Thread-6] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for GAGE2D
[ERROR] 09-05-2018 06:24:44 [ForkJoinPool.commonPool-worker-3] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for CT45A9
[ERROR] 09-05-2018 06:24:47 [ForkJoinPool.commonPool-worker-2] (ViewPoint.java:538) - Skipping trimming Segment List because no segments are selected for TSPY8
```

I checked some of these genes. All genes I checked were in repetitive regions and the initial list of digests contained the digest with the TSS. Therefore, it seems correct that they have no selected digests. However, I do not understand why this is interpreted as an error.

Apart from this, the viewpoints are shown in the list and taken into account for summary statistics, which is good because this is consistent with the simple approach.

**Comment by hansenp** [comment]
This is the code that produces the error messages shown above:

```
        // discard fragments except for the selected fragments and their immediate neighbors, i.e.,
        // retain one unselected digest on each end
        // this will keep the table from having lots of unselected fragments

        int LEN = restrictionSegmentList.size();
        int firstSelectedIndex = IntStream.range(0,LEN)
               .filter(i->restrictionSegmentList.get(i).isSelected())
                .findFirst().orElse(0);

        // The map reverses the order.
        int lastSelectedIndex = IntStream.range(0,LEN-1).
                map(i -> LEN - i - 1).
                filter(i->restrictionSegmentList.get(i).isSelected())
               .findFirst().orElse(0);


        if (firstSelectedIndex+lastSelectedIndex==0) {
            logger.error("Skipping trimming Segment List because no segments are selected for "+getTargetName());
        } else {
            int i = Math.max(0, firstSelectedIndex - 1);
            int j = Math.min(LEN, lastSelectedIndex + 2);// +2 because we want one more and range is (inclusive,exclusive)
            restrictionSegmentList  = IntStream.range(i, j).boxed().map(k -> restrictionSegmentList.get(k)).collect(Collectors.toList());
        }
```

For me, this is hard to read because of all the lambda notation. I think we should not report an error, if the TSS containing digest is not selected, because this may happen very often due to GC and repeat content.

Furthermore, the resizing of the digest list should not depend on digest selection but on the parameters specified by the user. We could add all digests that overlap the specified region plus the two adjacent digests in up- and downstream direction (analogous to the simple approach). This could already be done when the lists are initialized. Then no subsequent resizing is necessary.

**Comment by hansenp** [comment]
We removed all variables dealing with resolved viewpoints. Instead, we now have only the function hasValidDigest() that is used for calculation of summary statistics (and some other things). Viewpoints without selected digests are now shown in the list so as the user can examine them.

Some other issues occurred during the work on this issue but this seems to be solved (in branch iss302). Therefore, I will close it.
