### ISSUE TITLE
Zoom on wide viewpoints changes segment selection

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#345]
Affects both zoom-in and zoom-out.

![zoom](https://user-images.githubusercontent.com/5254933/45266005-b616cc00-b454-11e8-9ecb-ccdc48efdff9.gif)

**Comment by pnrobinson** [comment]
Was this with simple or extended? It is the expected behavior with extended, but not for simple -- @hansenp  ?

**Comment by steinha** [comment]
The example was generated with the extended approach. If this is intended behavior, then fine to close.

**Comment by hansenp** [comment]
As I pointed out earlier, I think it's not a good idea to couple zooming and selection of digests. However, we decided that this is intended behavior.

I checked this again for the extended approach and noticed that the check mark for _Manually revised_ on the analysis tab is not set, if digests are selected or deselected because of zooming.

**Comment by hansenp** [comment]
The check mark for _Manually revised_ is not set, if the selection of segments is changed because of zooming. I think this will require a call of the function `refreshVPTable`. That means that zooming will also become a bit slow for large projects (#338).

@pnrobinson, @steinha: What do you think?

**Comment by pnrobinson** [comment]
@hansenp  -- there is no reason not to want the score to reflect the relative amount that the viewpoint has been filled up with fragments, and so it seems ok to be to change the maxDistUp etc upon zooming. The alternative is to let the zoom do nothing to the selected fragments etc. A disadvantage of this is that there can be active segments that are not in the view.

**Comment by hansenp** [comment]
For the current version the score is not updated upon zooming because the update function is commented out.

```
    private void zoom(double factor) {
        logger.trace(String.format("Before zoom (factor %.2f) start=%d end =%d",factor,viewpoint.getStartPos(),viewpoint.getEndPos() ));
        this.viewpoint.zoom(factor);
        logger.trace(String.format("After zoom start=%d end =%d",viewpoint.getStartPos(),viewpoint.getEndPos() ));
        //updateScore();
        showColoredSegmentsInTable();
        showUcscView();
    }
```

If comment in this function and zoom out, the score is updated no matter if additional segments are selected. Furthermore, the scores changes in a strange way. For instance for a KLK2 viewpoint (DpnII). If I zoom out the first time, the score goes up, which seems to be okay because two additional segment were selected. If zoom out the second time, the score also goes up, which is strange because no segment was selected, and the range has become wider.

![peek 2018-09-13 18-45](https://user-images.githubusercontent.com/10495485/45502325-fee7c100-b783-11e8-947a-745cd785ce86.gif)

**Comment by hansenp** [comment]
For the calculation of the viewpoint score, the normal distribution is instantiated for each calculation of a score. Because we want to use the same distributions for each viewpoint, it's enough to instantiate only one distribution for the upstream and one for the downstream direction.

I implemented this on branch iss345. For this implementation, the normal distributions are instantiated only once after clicking on _Create Viewpoints!_ and saved in `Model` (`extendedNdUp` and `extendedNdDown`). Then I just replaced the normal distributions in `calculateViewpointScoreExtended` in class `ViewPoint`.

```
    public void calculateViewpointScoreExtended() {

        Double score = 0.0;
        // three standard deviations cover 99.7% of the data
        double sd = (double)upstreamNucleotideLength/6; // the factor 1/6 was chosen by eye
        double mean = 0; // shifts the normal distribution, so that almost the entire area under the curve is to the left of the y-axis
        logger.error(sd);
        NormalDistribution nDistUpstream = new NormalDistribution(mean,sd);
        sd = (double)downstreamNucleotideLength/6;
        NormalDistribution nDistDownstream = new NormalDistribution(mean,sd);


        nDistUpstream = model.getNormalDistributionExtendedUp();
        nDistDownstream = model.getNormalDistributionExtendedDown();
```


In order to verify this implementation, I calculated viewpoints for 32 human example genes hg19 and DpnII using the old and the new implementation. For genes on the forward strand, the viewpoints have the same score for both implementations but not for genes on the reverse strand.

Normal distributions instantiated within score function:
![image](https://user-images.githubusercontent.com/10495485/45562286-4fc1ed00-b84a-11e8-83db-4856a9a4ee86.png)

Normal distributions from Model:
![image](https://user-images.githubusercontent.com/10495485/45562351-813ab880-b84a-11e8-828d-711e07baef6a.png)

For instance, the gene MAPK1 is on the reverse strand and has a score of 81.0% for the normal distributions from the score function and a score of 89.6% for the normal distributions from Model.

I added the following logging statements:
```
        logger.error("nDistUpstream.getMean(): " + nDistUpstream.getMean());
        logger.error("nDistUpstream.getStandardDeviation(): " + nDistUpstream.getStandardDeviation());

        logger.error("nDistDownstream.getMean(): " + nDistDownstream.getMean());
        logger.error("nDistDownstream.getStandardDeviation(): " + nDistDownstream.getStandardDeviation()); 
```
This is what get for the normal distributions instantiated within score function:
```
[ERROR] 09-14-2018 18:37:15 [Thread-4] (ViewPoint.java:764) - nDistUpstream.getMean(): 0.0
[ERROR] 09-14-2018 18:37:15 [Thread-4] (ViewPoint.java:765) - nDistUpstream.getStandardDeviation(): 250.0
[ERROR] 09-14-2018 18:37:15 [Thread-4] (ViewPoint.java:767) - nDistDownstream.getMean(): 0.0
[ERROR] 09-14-2018 18:37:15 [Thread-4] (ViewPoint.java:768) - nDistDownstream.getStandardDeviation(): 833.3333333333334
```
And this is what I get for the normal distributions from Model:
```
[ERROR] 09-14-2018 18:41:33 [Thread-4] (ViewPoint.java:764) - nDistUpstream.getMean(): 0.0
[ERROR] 09-14-2018 18:41:33 [Thread-4] (ViewPoint.java:765) - nDistUpstream.getStandardDeviation(): 833.3333333333334
[ERROR] 09-14-2018 18:41:33 [Thread-4] (ViewPoint.java:767) - nDistDownstream.getMean(): 0.0
[ERROR] 09-14-2018 18:41:33 [Thread-4] (ViewPoint.java:768) - nDistDownstream.getStandardDeviation(): 250.0
```
For the normal distributions instantiated within score function, the distributions for the upstream and downstream direction seem get mixed up for genes on the reverse strand.

@pnrobinson: Did you take into account the strands for the implementation of the revised extended viewpoint score.

**Comment by pnrobinson** [comment]
It looks as if I did not take strand into account, which is a bug. One could fix the bug with something like this at line 771 of ViewPoint
```
 double upProb, downProb;
if (positive strand) {
upProb=getSegmentProbabilityUpstream(distance.get(0),distance.get(1),nDistUpstream);
downProb   = getSegmentProbabilityDownstream(distance.get(0),distance.get(1),nDistDownstream);
} else {
downProb=getSegmentProbabilityUpstream(distance.get(0),distance.get(1),nDistUpstream);
upProb   = getSegmentProbabilityDownstream(distance.get(0),distance.get(1),nDistDownstream);
}
```

**Comment by pnrobinson** [comment]
As discussed I am going to move the zoom from ViewPoint to the ViewPoint presenter so that zooming will not affect the ViewPoint object itself, only the range of genomic real estate this is displayed.

**Comment by pnrobinson** [comment]
@hansenp @steinha 
I reimplemented zoom so that it no longer changes the segments and the selection -- this seems to work fine now.
To do this I reimplemented a function in ViewPoint
OLD
```
public int getMinimumDisplayPosition() { return Math.min(getMinimumSelectedPosition(),this.genomicPos-upstreamNucleotideLength); }
```
NEW
```
 public int getMinimumDisplayPosition(double zoomfactor) {
        return Math.min(getMinimumSelectedPosition(),this.genomicPos-  (int)(upstreamNucleotideLength*zoomfactor));
  }
```
The current implementation of ``getMinimumSelectedPosition`` prevents us from zooming in to the extent that we show only part of the viewpoint
```
private int getMinimumSelectedPosition() {
        return getActiveSegments().stream().mapToInt(Segment::getStartPos).min().orElse(this.genomicPos-upstreamNucleotideLength);
    }
```
Do we want to keep this behavior (in which case we are done!) or do we want to allow users to zoom in more (in which case we need to remove the call to ``getMinimumSelectedPosition()``).

**Comment by pnrobinson** [comment]
If fixed this and zooming now seems to be working as desired
