### ISSUE TITLE
Alignability map 

### ISSUE THREAD

**Issue by rahmas36** [TheJacksonLaboratory/Gopher#370]
Hi, my name is Samir. I am a postdoctoral researcher at the Icahn School of Medicine at Mount Sinai. I am interested in doing Capture HiC and would like to use Gopher to design probes. I downloaded the genome file and indexed it, and downloaded the transcript definition file. What exactly is the alignability map? Where can I get this from?

**Comment by rahmas36** [comment]
I am using the Java app

**Comment by pnrobinson** [comment]
For human or mouse you should be able to download this directly from the app. There is a button here, Alignability map/Download
see
https://gopher.readthedocs.io/en/latest/02_gui_data.html

Did you try this?

**Comment by rahmas36** [comment]
Hi, thanks for your reply.  

I was able to find a directory http://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/
with alignability maps for different k-mers.

**Comment by hansenp** [comment]
Hi Samir,

first of all we need to now for which species you are going to design capture Hi-C probes. You sent a link for hg38. Therefore I suppose you need the map for human. For human and mouse, you can select hg19, hg38, mm9 and mm10. They will be downloaded automatically when you select the directory for the alignability map provided that there are no proxy issues. If necessary, you can specify a proxy via _Edit > Set Proxy_. Alignability maps for Zebrafish (danRer10) and western clawed frog (xenTro9) are also available.

For GOPHER, the maps need to be _bedGraph_ formatted. We prepared such files using _GEMTools_ and _kentUtils_ using a k-mer size of 50 and at most two allowed mismatches and uploaded them to a FTP server (ftp://ftp.jax.org/robinp/GOPHER/alignability_maps/). But as already mentioned you do not have to download the maps manually. The app will do this for you.

For each genomic position _p_, the maps contain the information to how many positions in the genome a kmer starting at position _p_ can be mapped. From this information, GOPHER calculates the average alignability for each probe and discards unspecific probes that can bind to many regions other than the actual target region due to repeats. This is done because such probes are not efficient.

I hope this answers your questions. If you have further questions, let us know. 

Best wishes,
Peter H.
