### ISSUE TITLE
Error when creating viewpoints

### ISSUE THREAD

**Issue by naiarabediaga** [TheJacksonLaboratory/Gopher#371]
Hello, 

This is Naiara, a postdoctoral researcher from the Walter and Eliza Hall Institute. 
I am about to perform a Capture HiC experiment and I would also like to use Gopher to design probes. I have uploaded the coordinates of 1230 GWAS hits, and I believe to have followed all the steps as per in the manual. The files downloaded in the path seemed to be OK. However, once I press the "create viewpoints" button, I keep getting the same error: 

"htsjdk.samtools.SAMException: Malformed query; start point 206782983 lies after endpoint 14967450"

I also get the same error when I upload "all protein-coding genes". 

I would be really grateful if anyone can help with this. 

Best

**Comment by hansenp** [comment]
Dear Naiara,

maybe something got mixed up with the genome builds. The error message indicates that GOPHER is trying to fetch the sequence of a nonexistent region that is located outside the chromosome. Which genome build do you have?

Please make sure that all information and paths specified under 'Data sources' belong to the same genome build. In order to get more information about this error, set the logging level to DEBUG ('Help -> Set logging level -> DEBUG').

Best wishes,
Peter H.

**Comment by naiarabediaga** [comment]
Dear Peter, 

Thanks a lot for your prompt reply. 

I must have defined the wrong paths in data sources. I have started a new project and downloaded the genome builds again (in a new path) and everything seems to be working fine now. 

Thank you so much 

Naiara

**Comment by hansenp** [comment]
Great! Good luck with your experiments!
