### ISSUE TITLE
Unnecessary error messages when reading in BED files

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#384]
When I try to read a BED file with only three columns via 'Enter BED file', I get the following error message:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/10495485/199770067-cd66aeb5-4e7b-44d2-a7b5-0380b1465dbe.png">

That is not correct. The BED format only requires 3 columns: https://genome.ucsc.edu/FAQ/FAQformat.html#format1

Also, when I try to read a BED file with a track annotation header line, I get an error message. This is annoying and unnecessary. Such lines always start with `browser` or `track` and could therefore simply be skipped.

**Comment by pnrobinson** [comment]
The way the application is written, we are using some of the data from BED6 format in this class because we are creating a GopherGene object,  GopherGene gene= new GopherGene(accession, accession, isNoncoding, chrom, strand);
and so the accession is taken from the fourtyh field of BED6. It would require a major rewrite to do this in another way and so it is probably best to leave the requirement for BED6 now unless there emerges a concrete need for BED3.
