### ISSUE TITLE
Probably unnecessary error message when reading BED files

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#388]
When I try to read a BED file that contains rows with the same names (column 4), I get the following error:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/10495485/199780704-f9eadb97-f0a3-4268-97bb-bf0478dc4b29.png">

If we don't do anything with the name in our code, we should remove this error message. The BED format does not require the names to be unique. The field is only used for display in the genome browser.

**Comment by pnrobinson** [comment]
This is because we currently allow one digest per gene and we are using a map with gene symbols that requires the gene symbols to be unique (BedFileParser). This makes sense for promoter-capture Hi-C. It does seem better to require the user to have unique names here (even though it is not required by BED). Is there a use case for having multiple identical names that we want to support? If so we would need to implement another function.
